# Generated by Django 4.2.5 on 2023-09-12 08:30


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("not_a_boring_blog", "0003_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="not_a_boring_blog.category"),
        ),
    ]
