# Generated by Django 4.2.4 on 2023-09-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0005_alter_comment_options_remove_comment_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
