# Generated by Django 4.2.4 on 2023-09-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0011_alter_repostrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repostrequest',
            options={'ordering': ['status', 'created_at']},
        ),
    ]
