# Generated by Django 4.2.4 on 2023-10-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0017_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_updated', '-created_at']},
        ),
    ]
